CREATE SCHEMA PUBLIC_AUDIT;
CREATE TABLE PUBLIC_AUDIT.USERS (
  ID                      INTEGER           NOT NULL,
  USERNAME                VARCHAR   (50)            ,
  PASSWORD                VARCHAR   (128)           ,
  CHANGED_ON              TIMESTAMP                 ,
  CHANGED_BY              INTEGER                   ,
  CREATED_ON              TIMESTAMP                 ,
  CREATED_BY              INTEGER
);
CREATE TABLE PUBLIC_AUDIT.OFFERS (
  ID                      BIGINT            NOT NULL,
  REF_NO                  VARCHAR   (255)   NOT NULL,
  CANTEEN                 BOOLEAN                   ,
  CURRENCY                VARCHAR   (3)             ,
  WEEKLY_HOURS            DECIMAL   (5, 3)  NOT NULL,
  DAILY_HOURS             DECIMAL   (5, 3)          ,
  DEDUCTION               NUMERIC   (2, 0)          ,
  EMPLOYER_NAME           VARCHAR   (255)   NOT NULL,
  EMPLOYER_ADDRESS        VARCHAR   (255)           ,
  EMPLOYER_ADDRESS_2      VARCHAR   (255)           ,
  EMPLOYER_BUSINESS       VARCHAR   (255)           ,
  EMPLOYER_EMPLOYEES_CNT  INTEGER                   ,
  EMPLOYER_WEBSITE        VARCHAR   (255)           ,
  FROM_DATE               DATE              NOT NULL,
  TO_DATE                 DATE              NOT NULL,
  FROM_DATE_2             DATE                      ,
  TO_DATE_2               DATE                      ,
  UNAVAILABLE_FROM        DATE                      ,
  UNAVAILABLE_TO          DATE                      ,
  LANGUAGE_1              VARCHAR   (255)   NOT NULL,
  LANGUAGE_1_LEVEL        VARCHAR   (1)     NOT NULL,
  LANGUAGE_1_OP           VARCHAR   (1)             ,
  LANGUAGE_2              VARCHAR   (255)           ,
  LANGUAGE_2_LEVEL        VARCHAR   (1)             ,
  LANGUAGE_2_OP           VARCHAR   (1)             ,
  LANGUAGE_3              VARCHAR   (255)           ,
  LANGUAGE_3_LEVEL        VARCHAR   (1)             ,
  LIVING_COST             DECIMAL   (12, 2)         ,
  LIVING_COST_FREQUENCY   INTEGER                   ,
  LODGING_BY              VARCHAR   (255)           ,
  LODGING_COST            DECIMAL   (12, 2)         ,
  LODGING_COST_FREQUENCY  INTEGER                   ,
  MAX_WEEKS               INTEGER           NOT NULL,
  MIN_WEEKS               INTEGER           NOT NULL,
  NEAREST_AIRPORT         VARCHAR   (255)           ,
  NEAREST_PUB_TRANSPORT   VARCHAR   (255)           ,
  NOMINATION_DEADLINE     DATE                      ,
  OTHER_REQUIREMENTS      VARCHAR   (500)           ,
  PAYMENT                 DECIMAL   (12, 2)         ,
  PAYMENT_FREQUENCY       VARCHAR   (1)             ,
  PREV_TRAINING_REQ       BOOLEAN                   ,
  WORK_DESCRIPTION        VARCHAR   (1000)  NOT NULL,
  WORKING_PLACE           VARCHAR   (255)           ,
  WORK_TYPE               CHARACTER (4)             ,
  STUDY_LEVELS            CHARACTER (3)     NOT NULL,
  STUDY_FIELDS            VARCHAR   (1000)  NOT NULL,
  SPECIALIZATIONS         VARCHAR   (1000)          ,
  CHANGED_ON              TIMESTAMP                 ,
  CHANGED_BY              INTEGER                   ,
  CREATED_ON              TIMESTAMP                 ,
  CREATED_BY              INTEGER
);
