create table offers (
        id                        bigint generated by default as identity (start with 1),
        canteen                   boolean,
        currency                  varchar(3),
        weekly_hours              decimal(5,3)  not null,
        daily_hours               decimal(5,3),
        deduction                 numeric(2,0),
        employer_address          varchar(255),
        employer_address_2        varchar(255),
        employer_business         varchar(255),
        employer_employees_cnt    integer,
        employer_name             varchar(255)  not null,
        employer_website          varchar(255),
        from_date                 date          NOT NULL,
        to_date                   date          NOT NULL,
        from_date_2               date,
        to_date_2                 date,
        gender                    varchar(1)    NOT NULL,
        unavailable_from          date,
        unavailable_to            date,
        language_1                varchar(255)  NOT NULL,
        language_1_level          varchar(1)    NOT NULL,
        language_1_op             varchar(1),
        language_2                varchar(255),
        language_2_level          varchar(1),
        language_2_op             varchar(1),
        language_3                varchar(255),
        language_3_level          varchar(1),
        living_cost               decimal(12,2),
        living_cost_frequency     integer,
        lodging_by                varchar(255),
        lodging_cost              decimal(12,2),
        lodging_cost_frequency    integer,
        max_weeks                 integer       NOT NULL,
        min_weeks                 integer       NOT NULL,
        nearest_airport           varchar(255),
        nearest_pub_transport     varchar(255),
        nomination_deadline       date          NULL,
        other_requirements        varchar(500),
        payment                   decimal(12,2),
        payment_frequency         varchar(1),
        prev_training_req         boolean,
        ref_no                    varchar(255)  not null,
        work_type                 varchar(1),
        work_description          varchar(1000) not null,
        working_place             varchar(255),
        primary key (id),
        unique (ref_no)
    );

CREATE TRIGGER offers_frequency_dependency_on_insert BEFORE INSERT ON offers
REFERENCING NEW AS newrow FOR EACH ROW
  WHEN((newrow.lodging_cost IS NOT NULL AND newrow.lodging_cost_frequency IS NULL)
    OR (newrow.living_cost IS NOT NULL AND newrow.living_cost_frequency IS NULL)
    OR (newrow.payment IS NOT NULL AND newrow.payment_frequency IS NULL))
    SIGNAL SQLSTATE '45000';

CREATE TRIGGER offers_frequency_dependency_on_update BEFORE UPDATE ON offers
REFERENCING NEW AS newrow OLD AS oldrow FOR EACH ROW
  WHEN((newrow.lodging_cost IS NOT NULL AND newrow.lodging_cost_frequency IS NULL)
    OR (newrow.living_cost IS NOT NULL AND newrow.living_cost_frequency IS NULL)
    OR (newrow.payment IS NOT NULL AND newrow.payment_frequency IS NULL))
    SIGNAL SQLSTATE '45000';