/*
 * =============================================================================
 * Copyright 1998-2015, IAESTE Internet Development Team. All rights reserved.
 * ----------------------------------------------------------------------------
 * Project: IntraWeb Services (iws-api) - net.iaeste.iws.api.dtos.Folder
 * -----------------------------------------------------------------------------
 * This software is provided by the members of the IAESTE Internet Development
 * Team (IDT) to IAESTE A.s.b.l. It is for internal use only and may not be
 * redistributed. IAESTE A.s.b.l. is not permitted to sell this software.
 *
 * This software is provided "as is"; the IDT or individuals within the IDT
 * cannot be held legally responsible for any problems the software may cause.
 * =============================================================================
 */
package net.iaeste.iws.api.dtos;

import net.iaeste.iws.api.constants.IWSConstants;
import net.iaeste.iws.api.enums.Privacy;
import net.iaeste.iws.api.util.AbstractVerification;
import net.iaeste.iws.api.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * @author  Kim Jensen / last $Author:$
 * @version $Revision:$ / $Date:$
 * @since   IWS 1.1
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Folder", propOrder = { "folderId", "parentId", "group", "foldername", "folders", "files", "privacy", "modified", "created" })
public final class Folder extends AbstractVerification {

    /** {@link IWSConstants#SERIAL_VERSION_UID}. */
    private static final long serialVersionUID = IWSConstants.SERIAL_VERSION_UID;

    /** Default allowed Actions for the Committee Request. */
    private static final Set<Privacy> allowed = EnumSet.of(Privacy.PRIVATE, Privacy.PROTECTED);

    @XmlElement(required = true, nillable = true)  private String folderId = null;
    @XmlElement(required = true, nillable = true)  private String parentId = null;
    @XmlElement(required = true, nillable = false) private Group group = null;
    @XmlElement(required = true, nillable = false) private String foldername = null;
    @XmlElement(required = true, nillable = true)  private List<Folder> folders = null;
    @XmlElement(required = true, nillable = true)  private List<File> files = null;
    @XmlElement(required = true, nillable = true)  private Privacy privacy = Privacy.PROTECTED;
    @XmlElement(required = true, nillable = true)  private Date modified = null;
    @XmlElement(required = true, nillable = true)  private Date created = null;

    // =========================================================================
    // Object Constructors
    // =========================================================================

    /**
     * Empty Constructor, to use if the setters are invoked. This is required
     * for WebServices to work properly.
     */
    public Folder() {
    }

    /**
     * Copy Constructor.
     *
     * @param folder Folder Object to copy
     */
    public Folder(final Folder folder) {
        if (folder != null) {
            folderId = folder.folderId;
            parentId = folder.parentId;
            group = new Group(folder.group);
            foldername = folder.foldername;
            folders = folder.folders;
            files = folder.files;
            privacy = folder.privacy;
            modified = folder.modified;
            created = folder.created;
        }
    }

    // =========================================================================
    // Standard Setters & Getters
    // =========================================================================

    /**
     * Sets the Folder Id for this Folder Object. The Id is generated by the IWS
     * upon saving the Folder.<br />
     *   Note, that if the value is invalid, then the method will thrown an
     * {@code IllegalArgumentException}.
     *
     * @param folderId Folder Id
     * @throws IllegalArgumentException if the Folder Id is invalid
     */
    public void setFolderId(final String folderId) throws IllegalArgumentException {
        ensureValidId("folderId", folderId);
        this.folderId = folderId;
    }

    public String getFolderId() {
        return folderId;
    }

    /**
     * Sets the Parent Folder Id for this Folder. If no ParentId is given, upon
     * creation of the Folder, the Group's root folder will be used.
     *
     * @param parentId Parent Folder Id
     */
    public void setParentId(final String parentId) throws IllegalArgumentException {
        ensureValidId("parentId", parentId);
        this.parentId = parentId;
    }

    public String getParentId() {
        return parentId;
    }

    /**
     * The owning group for this Folder. All Folder management is handled via
     * the Group, and this this is a mandatory field.<br />
     *   The method will throw an {@code IllegalArgumentException} if the Group
     * is either null or invalid.
     *
     * @param group Group
     * @throws IllegalArgumentException if null or not verifiable
     */
    public void setGroup(final Group group) throws IllegalArgumentException {
        ensureNotNullAndVerifiable("group", group);
        this.group = group;
    }

    public Group getGroup() {
        return group;
    }

    /**
     * The Foldername is mandatory in the IWS, and if not set or too long, the
     * method will throw an {@code IllegalArgumentException}.
     *
     * @param foldername Name of the Folder
     * @throws IllegalArgumentException if null, empty or longer than 100 characters
     */
    public void setFoldername(final String foldername) throws IllegalArgumentException {
        ensureNotNullOrEmptyOrTooLong("foldername", foldername, 100);
        this.foldername = foldername;
    }

    public String getFoldername() {
        return foldername;
    }

    /**
     * List of sub Folders for the current Folder. The list is set by the IWS,
     * and any changes to it will be ignored.
     *
     * @param folders List of sub Folders, empty if none.
     */
    public void setFolders(final List<Folder> folders) {
        this.folders = folders;
    }

    public List<Folder> getFolders() {
        return folders == null ? new ArrayList<Folder>(0) : folders;
    }

    /**
     * List of Files for the current Folder. The lis tis set by the IWS, and
     * any changes to it will be ignored.
     *
     * @param files List of Files, empty if none.
     */
    public void setFiles(final List<File> files) {
        this.files = files;
    }

    public List<File> getFiles() {
        return files == null ? new ArrayList<File>(0) : files;
    }

    /**
     * Sets the Privacy Flag for the Folder, it can be either Public or
     * Protected. Public means that if the Folder belongs to a Group which may
     * publish Folders & Files, then it will be publicly accessible. Private
     * means that the Folder is not accessible. By default, all Folders are
     * Private, making it a User opt-int choice to publish a Folder.<br />
     *   If a not allowed value is used, such as null or a different Privacy
     * enum value is used, then an {@code IllegalArgumentException} is thrown.
     *
     * @param privacy Privacy Value for the Folder, either Public or Protected
     * @throws IllegalArgumentException if value is null or not allowed
     */
    public void setPrivacy(final Privacy privacy) throws IllegalArgumentException {
        ensureNotNullAndContains("privacy", privacy, allowed);
        this.privacy = privacy;
    }

    public Privacy getPrivacy() {
        return privacy;
    }

    /**
     * Sets the last time the file was modified. Note, that this value is
     * controlled by the IWS, so any changes to it will be ignored.
     *
     * @param modified Date of last modification
     */
    public void setModified(final Date modified) {
        this.modified = modified;
    }

    public Date getModified() {
        return modified;
    }

    /**
     * Sets the time the file was created. Note, that this value is controlled
     * by the IWS, so any changes to it will be ignored.
     *
     * @param created Date of creation
     */
    public void setCreated(final Date created) {
        this.created = created;
    }

    public Date getCreated() {
        return created;
    }

    // =========================================================================
    // DTO required methods
    // =========================================================================

    /**
     * {@inheritDoc}
     */
    @Override
    public Map<String, String> validate() {
        final Map<String, String> validation = new HashMap<>(0);

        isNotNull(validation, "foldername", foldername);
        isNotNull(validation, "group", group);
        isNotNull(validation, "privacy", privacy);

        return validation;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean equals(final Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof Folder)) {
            return false;
        }

        final Folder folder = (Folder) obj;

        if (folderId != null ? !folderId.equals(folder.folderId) : folder.folderId != null) {
            return false;
        }
        if (parentId != null ? !parentId.equals(folder.parentId) : folder.parentId != null) {
            return false;
        }
        if (group != null ? !group.equals(folder.group) : folder.group != null) {
            return false;
        }
        if (foldername != null ? !foldername.equals(folder.foldername) : folder.foldername != null) {
            return false;
        }
        if (folders != null ? !folders.equals(folder.folders) : folder.folders != null) {
            return false;
        }
        if (files != null ? !files.equals(folder.files) : folder.files != null) {
            return false;
        }
        if (privacy != null ? !privacy.equals(folder.privacy) : folder.privacy != null) {
            return false;
        }
        if (modified != null ? !modified.equals(folder.modified) : folder.modified != null) {
            return false;
        }
        return !(created != null ? !created.equals(folder.created) : folder.created != null);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public int hashCode() {
        int result = IWSConstants.HASHCODE_INITIAL_VALUE;

        result = IWSConstants.HASHCODE_MULTIPLIER * result + ((folderId != null) ? folderId.hashCode() : 0);
        result = IWSConstants.HASHCODE_MULTIPLIER * result + ((parentId != null) ? parentId.hashCode() : 0);
        result = IWSConstants.HASHCODE_MULTIPLIER * result + ((group != null) ? group.hashCode() : 0);
        result = IWSConstants.HASHCODE_MULTIPLIER * result + (foldername != null ? foldername.hashCode() : 0);
        result = IWSConstants.HASHCODE_MULTIPLIER * result + (folders != null ? folders.hashCode() : 0);
        result = IWSConstants.HASHCODE_MULTIPLIER * result + (files != null ? files.hashCode() : 0);
        result = IWSConstants.HASHCODE_MULTIPLIER * result + (privacy != null ? privacy.hashCode() : 0);
        result = IWSConstants.HASHCODE_MULTIPLIER * result + (modified != null ? modified.hashCode() : 0);
        result = IWSConstants.HASHCODE_MULTIPLIER * result + (created != null ? created.hashCode() : 0);

        return result;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String toString() {
        return "Folder{" +
                "folderId='" + folderId + '\'' +
                ", parentId='" + parentId + '\'' +
                ", group='" + group + '\'' +
                ", foldername='" + foldername + '\'' +
                ", folders=" + folders +
                ", files=" + files +
                ", privacy=" + privacy +
                ", modified=" + modified +
                ", created=" + created +
                '}';
    }
}
